name: Build String Finder
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Обновили до v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile
        run: cl.exe /EHsc /W3 main.cpp /Fe:StringFinder.exe user32.lib advapi32.lib

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Вот здесь была ошибка, теперь v4
        with:
          name: StringFinder-Build
          path: StringFinder.exe
